# Generated by Django 6.0.5 on 2026-05-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_sessionparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countingsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countingsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
